parameters:
    jwt_secret: '%env(JWT_SECRET)%'  # <-- Déclaration du paramètre à partir de l'env

services:
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les services (Command, Event, etc.)

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JwtService:
        arguments:
            $secret: '%jwt_secret%'  # <-- Injection du paramètre dans le constructeur

    # services.yaml
# App\EventListener\CorsListener:
#     tags:
#         - { name: kernel.event_listener, event: kernel.response }
