services:
    _defaults:
        autowire: true  # Active l'autowiring
        autoconfigure: true  # Active l'autoconfiguration
        public: false  # Par défaut, tous les services sont privés

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']  # Enregistre tous les contrôleurs dans le container

    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']  # Ajoute tous les repositories automatiquement

