# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Active la protection CSRF pour les formulaires
    form:
        csrf_protection: true

    # Activation de la protection CSRF globalement (si nécessaire)
    csrf_protection: true

    # Session : gestion par défaut avec stockage natif
    session:
        handler_id: null  # Utilisation du gestionnaire par défaut
        storage_factory_id: session.storage.factory.native  # Utilise le stockage natif des sessions

    # Autres options que tu peux activer si nécessaire
    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file  # Utilise une session simulée pour les tests
